name: detroitd
services:
  user-service:
    build:
      context: packages/UserService
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "mcos"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
    depends_on:
      - db
  db:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mcos"
  pgadmin:
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: "80"
      POSTGRES_DB: "mcos"
    ports:
      - "15432:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  haproxy:
    build:
      context: services/haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./services/haproxy/ssl:/usr/local/etc/haproxy/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - user-service
      - db
      - pgadmin

volumes:
  pgadmin:
